# Generated by Django 5.2.5 on 2025-08-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
